name: ravello
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2  # State management (Cart, Favorite, dll)
  slide_to_act: ^2.0.2
  http: ^1.2.2  # ğŸ”¹ Tambahan: untuk koneksi API (login/register, dll)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ravello_logo.png
    - assets/images/google_logo.png
    - assets/images/Profile.png
    - assets/images/Sepatu.png
    - assets/images/Gelang_rajut.png
    - assets/images/Jersey.png
    - assets/images/Rolex_KW.png
    - assets/images/Dana.png
    - assets/images/Paylater.png
    - assets/images/OVO.png
    - assets/images/COD.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
